# Generated by Django 3.2.6 on 2021-10-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=10)),
                ('esalary', models.FloatField()),
                ('eaddress', models.CharField(max_length=20)),
            ],
        ),
    ]
